### ISSUE TITLE
ufdbGuard support?

### ISSUE THREAD

**Issue by mrbluecoat** [luigi1809/webfilter-ng#2]
Awesome project!  SquidGuard is great but hasn't been updated in the last decade and has public security vulnerabilities.  Any thoughts on updating your project to support its spiritual successor: ufdbGuard

Others have taken this approach: https://github.com/NethServer/dev/issues/5171

**Comment by luigi1809** [comment]
Thanks for the support.

I recommand to use the dns option as SquidGuard and ufdbGuard are based on url filter list. It is difficult to maintain fitler list.

I won't have a lot of time to add support for ufdbGuard. 

If you want, you can do a pull request with the ufdbGuard option. Create ufdbGuardWebGuard bash script that echo DROP/ACCEPT and write to log. Add option in makefile and add the doc

**Comment by mrbluecoat** [comment]
If I ever need this functionality I'll go with [Webshrinker](https://www.webshrinker.com/) which is cheaper, has a better API, and is more accurate.

**Comment by luigi1809** [comment]
Web service API is better idea. Will have a look at webshrinker
What about categorify.org from cleanbrowsing which is free ?

**Comment by mrbluecoat** [comment]
It's admittedly subjective, but PG seems a bit low for https://categorify.org/api?website=victoriassecret.com

**Comment by mrbluecoat** [comment]
Others I looked at: https://mrbluecoat.blogspot.com/2019/11/url-filtering-services.html

**Comment by mrbluecoat** [comment]
That said, if we had a config file that accepted a rating threshold and category array it could work.  Something like `{"language":false,"violence":false,"nudity":false,"adult":false, rating:"PG", blacklist: ["Lingerie"]}`

We'd also want to cache results for a time to reduce the likelihood of exceeding the 200 API calls limit.
