### ISSUE TITLE
unbound support?

### ISSUE THREAD

**Issue by mrbluecoat** [luigi1809/webfilter-ng#3]
Any guidance for using unbound instead of BIND for the webfilter-ng DNS resolver?

**Comment by luigi1809** [comment]
webfilter-ng is compatible with any kind of DNS server. The requirement is that webfilter-ng and DNS server run on the same machine.

If you add a good tutorial to install unbound, I can add it to the doc

**Comment by mrbluecoat** [comment]
I'm now leaning toward knot-resolver
