### ISSUE TITLE
DNS cache

### ISSUE THREAD

**Issue by mrbluecoat** [luigi1809/webfilter-ng#8]
The readme mentions "webfilter-ng will read the dns cache of bind9" but I don't see "/var/cache/bind" mentioned in _webfilter-ng.c_.  My C programming is as good as my iptables dojo so I'm probably missing something obvious.  Can you point me in the right direction?  I'm interested in trying dnsmasq and knot-resolver...

**Comment by luigi1809** [comment]
Any local dns is OK as long as it is doing cache. Dnsmasq and knot should do it.

Webfiler-ng is C calls webGuard shell script, which is a copy of dnsWebGuard/dnsCategorifyWeGuard. Then shell script does a dig command to query local DNS, which has the response in cache
